export PATH=~/bin:/opt/node/bin:/opt/homebrew/bin:$PATH
export EDITOR=emacs
export PROMPT='%~ %# '
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS
setopt interactive_comments
